"""add_is_edited_to_comment

Revision ID: 54165152f3ac
Revises: 700b15ec14b3
Create Date: 2025-04-16 21:02:52.651727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54165152f3ac'
down_revision: Union[str, None] = '700b15ec14b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('is_edited', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'is_edited')
    # ### end Alembic commands ###
