"""Change mapping objects

Revision ID: 0247f5947c58
Revises: 66acd7c8db14
Create Date: 2025-04-13 17:47:14.055509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0247f5947c58'
down_revision: Union[str, None] = '66acd7c8db14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_commentmention_id', table_name='commentmention')
    op.drop_column('commentmention', 'id')
    op.drop_index('ix_taskassignee_id', table_name='taskassignee')
    op.drop_column('taskassignee', 'id')
    op.drop_index('ix_taskwatcher_id', table_name='taskwatcher')
    op.drop_column('taskwatcher', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskwatcher', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_taskwatcher_id', 'taskwatcher', ['id'], unique=False)
    op.add_column('taskassignee', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_taskassignee_id', 'taskassignee', ['id'], unique=False)
    op.add_column('commentmention', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_commentmention_id', 'commentmention', ['id'], unique=False)
    # ### end Alembic commands ###
